// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBukUWDT3rBxdqtSLXTt6XKD9DFeMMG3D4',
    appId: '1:130375324659:web:25045672d84144c84d7886',
    messagingSenderId: '130375324659',
    projectId: 'flutter-firebase-8410e',
    authDomain: 'flutter-firebase-8410e.firebaseapp.com',
    storageBucket: 'flutter-firebase-8410e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYgEqWVXLDJUq2fO8-UKOXOkZOceSvnPk',
    appId: '1:130375324659:android:6a7f074d341fbdcf4d7886',
    messagingSenderId: '130375324659',
    projectId: 'flutter-firebase-8410e',
    storageBucket: 'flutter-firebase-8410e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfXb010KFwRbYO1Br0Wn4QsZp9r3nBe9k',
    appId: '1:130375324659:ios:a3ca389dbf3b0b694d7886',
    messagingSenderId: '130375324659',
    projectId: 'flutter-firebase-8410e',
    storageBucket: 'flutter-firebase-8410e.appspot.com',
    androidClientId: '130375324659-a7adi7pavmnepgpft8hvb3a3b2gno24q.apps.googleusercontent.com',
    iosClientId: '130375324659-8anno6478ufba4kiva0jdvah6ge0upsf.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatingappFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfXb010KFwRbYO1Br0Wn4QsZp9r3nBe9k',
    appId: '1:130375324659:ios:a3ca389dbf3b0b694d7886',
    messagingSenderId: '130375324659',
    projectId: 'flutter-firebase-8410e',
    storageBucket: 'flutter-firebase-8410e.appspot.com',
    androidClientId: '130375324659-a7adi7pavmnepgpft8hvb3a3b2gno24q.apps.googleusercontent.com',
    iosClientId: '130375324659-8anno6478ufba4kiva0jdvah6ge0upsf.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatingappFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBukUWDT3rBxdqtSLXTt6XKD9DFeMMG3D4',
    appId: '1:130375324659:web:a4bf609b512107b74d7886',
    messagingSenderId: '130375324659',
    projectId: 'flutter-firebase-8410e',
    authDomain: 'flutter-firebase-8410e.firebaseapp.com',
    storageBucket: 'flutter-firebase-8410e.appspot.com',
  );
}
